name: Build

on:
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the main branch
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
      
      # install dependencies
      - name: Install dependencies
        run: npm install
      
      # build and minify
      - name: Build
        run: npm run build
      
      # push the static website to the dist branch
      - name: Push to dist branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: dist
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}